# Generated by Django 5.1.2 on 2024-11-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupones',
            fields=[
                ('cupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cupones',
            },
        ),
    ]
