# Generated by Django 5.1.2 on 2024-11-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('facturacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('calle', models.CharField(max_length=255)),
                ('apartamento', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(max_length=255)),
                ('cp', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facturacion',
            },
        ),
    ]
