# Generated by Django 5.1.2 on 2024-11-06 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_carrito_carritoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('envio_id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_envio', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('metodo_envio', models.CharField(max_length=255)),
                ('estado_envio', models.CharField(max_length=255)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.compra')),
            ],
            options={
                'db_table': 'envios',
            },
        ),
    ]
