# Generated by Django 5.1.2 on 2024-11-06 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=255)),
                ('estado_pago', models.CharField(max_length=255)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.compra')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
    ]
