# Generated by Django 5.1.2 on 2024-11-06 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resenas',
            fields=[
                ('resena_id', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
            options={
                'db_table': 'resenas',
            },
        ),
    ]
